name: Build web image and push to registry

on:
  push:

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: bjvanbemmel/benkyou-web:latest

  run-container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Run container
        run: |
          docker run --rm -d -p ${{ vars.WEB_PORT }}:3000 bjvanbemmel/benkyou-web:latest
