name: Run API unit tests

on:
  push:

jobs:
  go-test:
    runs-on: self-hosted
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Generate SQLC models
        run: |
          docker run --rm --user 1000 -v ./api:/src -w /src sqlc/sqlc generate
      -
        name: Go test
        run: |
          docker run --rm -v ./api:/app golang:1.22-alpine3.20 sh -c 'cd /app && go test -v ./...'
