name: Run API unit tests

on:
  push:
  pull_request:

jobs:
  go-test:
    runs-on: self-hosted
    steps:
      -
        name: Go test
        run: |
          docker run -v ./:/app golang:1.22-alpine3.20 sh -c 'cd /app && go test -v ./...'
